export const routes = {
  welcome: '/welcome',
  login: '/login',
  noAccount: '/no-account',
  signup: '/signup',
  verifyOtp: '/verify-otp',
  roleSelection: '/role-selection',
  addProperty: '/add-property',
  confirmLocation: '/confirm-location',
  propertyAdded: '/property-added',
  joinProperty: '/join-property',
  allSet: '/all-set',
  home: '/home',
  workerDashboard: '/worker-dashboard',
  workerPropertyDetails: '/worker-property-details',
  ownerPropertyDetails: '/owner-property-details',
  propertySpaces: '/property-spaces',
  addPropertyItem: '/add-property-item',
  manageWorkers: '/manage-workers',
  wokrerInspectionChecklist: '/inspection-checklist',
  workerSpaceCapture: '/worker-space-capture',
} as const;